# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{smart_monkey}
  version_path = File.join(File.dirname(__FILE__), "VERSION")
  s.version = File.read(version_path)

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["vigossjjj"]
  s.date = %q{2015-06-01}
  s.default_executable = %q{smart_monkey}
  s.description = %q{iOS Monkey test tool base on UIAutomation.}
  s.email = %q{jiangyunpeng@58.com}
  s.executables = ["smart_monkey"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md",
  ]
  s.files = Dir.glob("{bin,lib,spec}/**/*") +
    %w(VERSION LICENSE.txt README.md Troubleshooting.md reset.sh Rakefile)
  s.homepage = %q{https://github.com/vigossjjj/CrashMonkey4IOS}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{Monkey Test For iOS Application}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<erubis>, [">= 2.7.0"])
      s.add_runtime_dependency(%q<json>, [">= 1.7.0"])
      s.add_development_dependency(%q<rspec>, ["~> 2.8.0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
    else
      s.add_dependency(%q<erubis>, [">= 2.7.0"])
      s.add_dependency(%q<json>, [">= 1.7.0"])
      s.add_dependency(%q<rspec>, ["~> 2.8.0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
      if RUBY_VERSION > '1.9' then
        s.add_dependency(%q<simplecov>, [">= 0"])
      else
        s.add_dependency(%q<rcov>, [">= 0"])
      end
    end
  else
    s.add_dependency(%q<erubis>, [">= 2.7.0"])
    s.add_dependency(%q<json>, [">= 1.7.0"])
    s.add_dependency(%q<rspec>, ["~> 2.8.0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
    s.add_dependency(%q<rcov>, [">= 0"])
  end
end

